CLIENT_HELLO = 0
CLIENT_GOODBYE = 1
CLIENT_ROOM_INFO = 2
CLIENT_MESSAGE = 3
CLIENT_ENCRYPTED_MESSAGE = 4
CLIENT_KEYS = 5

SERVER_HELLO = 0
SERVER_GOODBYE = 1
SERVER_ROOM_INFO = 2
SERVER_MESSAGE = 3
SERVER_ENCRYPTED_MESSAGE = 4
SERVER_KEYS = 5
